create table "public"."profiles" (
    "id" bigint generated by default as identity not null,
    "full_name" text,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null
);


alter table "public"."profiles" enable row level security;

create table "public"."tenant_permission" (
    "id" bigint generated by default as identity not null,
    "profile_id" bigint not null,
    "tenant_id" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."tenant_permission" enable row level security;

create table "public"."tenants" (
    "id" text not null,
    "name" text not null,
    "domain" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."tenants" enable row level security;

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_user_id_key ON public.profiles USING btree (user_id);

CREATE UNIQUE INDEX tenant_permission_pkey ON public.tenant_permission USING btree (id);

CREATE UNIQUE INDEX tenants_domain_key ON public.tenants USING btree (domain);

CREATE UNIQUE INDEX tenants_pkey ON public.tenants USING btree (id);

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."tenant_permission" add constraint "tenant_permission_pkey" PRIMARY KEY using index "tenant_permission_pkey";

alter table "public"."tenants" add constraint "tenants_pkey" PRIMARY KEY using index "tenants_pkey";

alter table "public"."profiles" add constraint "profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_user_id_fkey";

alter table "public"."profiles" add constraint "profiles_user_id_key" UNIQUE using index "profiles_user_id_key";

alter table "public"."tenant_permission" add constraint "tenant_permission_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) not valid;

alter table "public"."tenant_permission" validate constraint "tenant_permission_profile_id_fkey";

alter table "public"."tenant_permission" add constraint "tenant_permission_profile_id_fkey1" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tenant_permission" validate constraint "tenant_permission_profile_id_fkey1";

alter table "public"."tenant_permission" add constraint "tenant_permission_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) not valid;

alter table "public"."tenant_permission" validate constraint "tenant_permission_tenant_id_fkey";

alter table "public"."tenant_permission" add constraint "tenant_permission_tenant_id_fkey1" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tenant_permission" validate constraint "tenant_permission_tenant_id_fkey1";

alter table "public"."tenants" add constraint "tenants_domain_key" UNIQUE using index "tenants_domain_key";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."tenant_permission" to "anon";

grant insert on table "public"."tenant_permission" to "anon";

grant references on table "public"."tenant_permission" to "anon";

grant select on table "public"."tenant_permission" to "anon";

grant trigger on table "public"."tenant_permission" to "anon";

grant truncate on table "public"."tenant_permission" to "anon";

grant update on table "public"."tenant_permission" to "anon";

grant delete on table "public"."tenant_permission" to "authenticated";

grant insert on table "public"."tenant_permission" to "authenticated";

grant references on table "public"."tenant_permission" to "authenticated";

grant select on table "public"."tenant_permission" to "authenticated";

grant trigger on table "public"."tenant_permission" to "authenticated";

grant truncate on table "public"."tenant_permission" to "authenticated";

grant update on table "public"."tenant_permission" to "authenticated";

grant delete on table "public"."tenant_permission" to "service_role";

grant insert on table "public"."tenant_permission" to "service_role";

grant references on table "public"."tenant_permission" to "service_role";

grant select on table "public"."tenant_permission" to "service_role";

grant trigger on table "public"."tenant_permission" to "service_role";

grant truncate on table "public"."tenant_permission" to "service_role";

grant update on table "public"."tenant_permission" to "service_role";

grant delete on table "public"."tenants" to "anon";

grant insert on table "public"."tenants" to "anon";

grant references on table "public"."tenants" to "anon";

grant select on table "public"."tenants" to "anon";

grant trigger on table "public"."tenants" to "anon";

grant truncate on table "public"."tenants" to "anon";

grant update on table "public"."tenants" to "anon";

grant delete on table "public"."tenants" to "authenticated";

grant insert on table "public"."tenants" to "authenticated";

grant references on table "public"."tenants" to "authenticated";

grant select on table "public"."tenants" to "authenticated";

grant trigger on table "public"."tenants" to "authenticated";

grant truncate on table "public"."tenants" to "authenticated";

grant update on table "public"."tenants" to "authenticated";

grant delete on table "public"."tenants" to "service_role";

grant insert on table "public"."tenants" to "service_role";

grant references on table "public"."tenants" to "service_role";

grant select on table "public"."tenants" to "service_role";

grant trigger on table "public"."tenants" to "service_role";

grant truncate on table "public"."tenants" to "service_role";

grant update on table "public"."tenants" to "service_role";


